function [fitresult, gof] = FitStim(tavg, dfavg1)
%CREATEFIT(TAVG,DFAVG1)
%  Create a fit.
%
%  Data for 'FitStim' fit:
%      X Input : tavg
%      Y Output: dfavg1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 16-Nov-2016 13:34:55


%% Fit: 'FitStim'.
[xData, yData] = prepareCurveData( tavg, dfavg1 );

% Set up fittype and options.
ft = fittype( 'a.*heaviside(c-x)+b*heaviside(x-c).*exp(-x./d)', 'independent', 'x', 'dependent', 'y' );
excludedByRule = yData > 3*std(yData);
excludedPoints = excludedByRule;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.StartPoint = [0.398905400307512 0.576443150588702 0.357381103830764 0.754686681982361];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'FitStim' );
% h = plot( fitresult, xData, yData );
% legend( h, 'dfavg1 vs. tavg', 'FitStim', 'Location', 'NorthEast' );
% % Label axes
% xlabel Tavg
% ylabel dFavg
% grid on


